// Code generated by "stringer -type=AttributeType"; DO NOT EDIT.

package provparse

import "strconv"

const _AttributeType_name = "TypeInvalidTypeBoolTypeIntTypeFloatTypeStringTypeListTypeMapTypeSet"

var _AttributeType_index = [...]uint8{0, 11, 19, 26, 35, 45, 53, 60, 67}

func (i AttributeType) String() string {
	if i < 0 || i >= AttributeType(len(_AttributeType_index)-1) {
		return "AttributeType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AttributeType_name[_AttributeType_index[i]:_AttributeType_index[i+1]]
}
